name: oscode2
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=3.2.0 <4.0.0'
  ##sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  pin_code_fields: ^8.0.1
  flutter_rating_bar: ^4.0.1
  smooth_page_indicator: ^1.1.0
  flutter_svg_provider: ^1.0.7
  readmore: ^2.2.0
  google_maps_flutter: ^2.5.0
  qr_flutter: ^4.1.0
  another_stepper: ^1.2.2
  intl: ^0.19.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: AirbnbCereal_W_Md
      fonts: 
        - asset: assets/fonts/AirbnbCerealWMd.ttf
          weight: 500
    - family: AirbnbCereal_W_Bk
      fonts: 
        - asset: assets/fonts/AirbnbCerealWBk.ttf
          weight: 400
    - family: SF Pro Display
      fonts: 
        - asset: assets/fonts/SFProDisplayRegular.ttf
          weight: 400
        - asset: assets/fonts/SFProDisplaySemibold.ttf
          weight: 600
    - family: SF Pro Text
      fonts: 
        - asset: assets/fonts/SFProTextBold.ttf
          weight: 700
    - family: AirbnbCereal_W_Lt
      fonts: 
        - asset: assets/fonts/AirbnbCerealWLt.ttf
          weight: 300
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
    - family: Lato
      fonts: 
        - asset: assets/fonts/LatoMedium.ttf
          weight: 500
    - family: Nunito Sans
      fonts: 
        - asset: assets/fonts/NunitoSansRegular.ttf
          weight: 400
        - asset: assets/fonts/NunitoSansSemiBold.ttf
          weight: 600
    - family: Oxygen
      fonts: 
        - asset: assets/fonts/OxygenRegular.ttf
          weight: 400
