import 'package:flutter/material.dart';import 'package:oscode2/core/app_export.dart';import 'package:oscode2/widgets/app_bar/appbar_leading_image.dart';import 'package:oscode2/widgets/app_bar/custom_app_bar.dart';import 'package:oscode2/widgets/custom_elevated_button.dart';import 'package:oscode2/widgets/custom_icon_button.dart';import 'package:oscode2/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class SignUpScreen extends StatelessWidget {SignUpScreen({Key? key}) : super(key: key);

TextEditingController fullNameController = TextEditingController();

TextEditingController emailController = TextEditingController();

TextEditingController passwordController = TextEditingController();

TextEditingController confirmPasswordController = TextEditingController();

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(extendBody: true, extendBodyBehindAppBar: true, resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: SizeUtils.width, height: SizeUtils.height, decoration: BoxDecoration(color: theme.colorScheme.primary, image: DecorationImage(image: AssetImage(ImageConstant.imgSignUp), fit: BoxFit.cover)), child: Form(key: _formKey, child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 28.h, vertical: 12.v), child: Column(children: [Align(alignment: Alignment.centerLeft, child: SizedBox(height: 32.v, width: 83.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 3.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgG430, height: 1.adaptSize, width: 1.adaptSize), CustomImageView(imagePath: ImageConstant.imgPath534, height: 1.adaptSize, width: 1.adaptSize)]))), Align(alignment: Alignment.center, child: Text("Sign up", style: theme.textTheme.headlineSmall))]))), SizedBox(height: 17.v), _buildFullName(context), SizedBox(height: 19.v), _buildEmail(context), SizedBox(height: 19.v), _buildPassword(context), SizedBox(height: 19.v), _buildConfirmPassword(context), SizedBox(height: 40.v), SizedBox(height: 58.v, width: 271.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: Container(height: 58.v, width: 271.h, padding: EdgeInsets.all(14.h), decoration: AppDecoration.outlineIndigoF.copyWith(borderRadius: BorderRadiusStyle.roundedBorder15), child: CustomIconButton(height: 30.adaptSize, width: 30.adaptSize, padding: EdgeInsets.all(8.h), alignment: Alignment.centerRight, child: CustomImageView(imagePath: ImageConstant.imgArrowleft)))), Align(alignment: Alignment.center, child: Text("Sign up".toUpperCase(), style: theme.textTheme.titleMedium))])), Spacer(), Text("OR", style: CustomTextStyles.titleMediumGray50001), SizedBox(height: 22.v), _buildLoginWithGoogle(context), SizedBox(height: 20.v), GestureDetector(onTap: () {onTapTxtAlreadyhavean(context);}, child: RichText(text: TextSpan(children: [TextSpan(text: "Already have an account?  ", style: CustomTextStyles.bodyMediumGray9000315), TextSpan(text: "Signin", style: CustomTextStyles.bodyMediumIndigoA2000315_1)]), textAlign: TextAlign.left)), SizedBox(height: 32.v)])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: double.maxFinite, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftGray90003, margin: EdgeInsets.fromLTRB(24.h, 9.v, 329.h, 9.v))); } 
/// Section Widget
Widget _buildFullName(BuildContext context) { return CustomTextFormField(controller: fullNameController, hintText: "Full name", hintStyle: CustomTextStyles.bodyMediumGray600, prefix: Container(margin: EdgeInsets.fromLTRB(15.h, 17.v, 14.h, 17.v), child: CustomImageView(imagePath: ImageConstant.imgLock, height: 22.adaptSize, width: 22.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 56.v)); } 
/// Section Widget
Widget _buildEmail(BuildContext context) { return CustomTextFormField(controller: emailController, hintText: "abc@email.com", hintStyle: CustomTextStyles.bodyMediumGray600, textInputType: TextInputType.emailAddress, prefix: Container(margin: EdgeInsets.fromLTRB(15.h, 17.v, 14.h, 17.v), child: CustomImageView(imagePath: ImageConstant.imgCheckmark, height: 22.adaptSize, width: 22.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 56.v)); } 
/// Section Widget
Widget _buildPassword(BuildContext context) { return CustomTextFormField(controller: passwordController, hintText: "Your password", hintStyle: CustomTextStyles.bodyMediumGray600, textInputType: TextInputType.visiblePassword, prefix: Container(margin: EdgeInsets.fromLTRB(15.h, 17.v, 14.h, 17.v), child: CustomImageView(imagePath: ImageConstant.imgLocation, height: 22.adaptSize, width: 22.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 56.v), suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 16.v, 16.h, 16.v), child: CustomImageView(imagePath: ImageConstant.imgEye, height: 24.adaptSize, width: 24.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 56.v), obscureText: true, contentPadding: EdgeInsets.symmetric(vertical: 18.v)); } 
/// Section Widget
Widget _buildConfirmPassword(BuildContext context) { return CustomTextFormField(controller: confirmPasswordController, hintText: "Confirm password", hintStyle: CustomTextStyles.bodyMediumGray600, textInputAction: TextInputAction.done, textInputType: TextInputType.visiblePassword, prefix: Container(margin: EdgeInsets.fromLTRB(15.h, 17.v, 14.h, 17.v), child: CustomImageView(imagePath: ImageConstant.imgLocation, height: 22.adaptSize, width: 22.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 56.v), suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 16.v, 16.h, 16.v), child: CustomImageView(imagePath: ImageConstant.imgEye, height: 24.adaptSize, width: 24.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 56.v), obscureText: true, contentPadding: EdgeInsets.symmetric(vertical: 18.v)); } 
/// Section Widget
Widget _buildLoginWithGoogle(BuildContext context) { return CustomElevatedButton(height: 56.v, text: "Login with Google", margin: EdgeInsets.symmetric(horizontal: 23.h), leftIcon: Container(margin: EdgeInsets.only(right: 20.h), child: CustomImageView(imagePath: ImageConstant.imgGoogle, height: 26.adaptSize, width: 26.adaptSize)), buttonStyle: CustomButtonStyles.outlineBlueGrayF, buttonTextStyle: CustomTextStyles.bodyLargeAirbnbCerealWBkGray90003); } 
/// Navigates to the signInScreen when the action is triggered.
onTapTxtAlreadyhavean(BuildContext context) { Navigator.pushNamed(context, AppRoutes.signInScreen); } 
 }
