import 'package:flutter/material.dart';import 'package:oscode2/core/app_export.dart';import 'package:oscode2/widgets/custom_elevated_button.dart';import 'package:oscode2/widgets/custom_switch.dart';import 'package:oscode2/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class SignInScreen extends StatelessWidget {SignInScreen({Key? key}) : super(key: key);

TextEditingController emailEditTextController = TextEditingController();

TextEditingController passwordEditTextController = TextEditingController();

bool isSelectedSwitch = false;

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: Form(key: _formKey, child: SizedBox(width: double.maxFinite, child: SingleChildScrollView(child: Column(children: [_buildWidgetStack(context), SizedBox(height: 13.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 32.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgG430, height: 1.adaptSize, width: 1.adaptSize), CustomImageView(imagePath: ImageConstant.imgPath534, height: 1.adaptSize, width: 1.adaptSize)]))), SizedBox(height: 13.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 29.h), child: Text("Sign in", style: theme.textTheme.headlineSmall))), SizedBox(height: 18.v), _buildEmailEditText(context), SizedBox(height: 4.v), SizedBox(height: 588.v, width: double.maxFinite, child: Stack(alignment: Alignment.bottomLeft, children: [Opacity(opacity: 0.5, child: CustomImageView(imagePath: ImageConstant.imgEllipse70322x44, height: 322.v, width: 44.h, alignment: Alignment.bottomRight, margin: EdgeInsets.only(bottom: 80.v))), Opacity(opacity: 0.4, child: CustomImageView(imagePath: ImageConstant.imgEllipse71173x82, height: 173.v, width: 82.h, alignment: Alignment.bottomLeft)), Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(left: 51.h, right: 51.h, bottom: 150.v), child: Column(mainAxisSize: MainAxisSize.min, children: [Text("OR", style: CustomTextStyles.titleMediumGray50001), SizedBox(height: 22.v), _buildLoginWithGoogleButton(context), SizedBox(height: 20.v), GestureDetector(onTap: () {onTapTxtDonthaveanaccount(context);}, child: RichText(text: TextSpan(children: [TextSpan(text: "Don’t have an account?  ", style: CustomTextStyles.bodyMediumGray9000315), TextSpan(text: "Sign up", style: CustomTextStyles.bodyMediumIndigoA2000315_1)]), textAlign: TextAlign.left))]))), _buildSignInButton(context), _buildPasswordEditText(context), Opacity(opacity: 0.7, child: CustomImageView(imagePath: ImageConstant.imgEllipse69209x203, height: 209.v, width: 203.h, alignment: Alignment.topRight)), _buildRememberMeRow(context)]))])))))); } 
/// Section Widget
Widget _buildWidgetStack(BuildContext context) { return SizedBox(height: 146.v, width: double.maxFinite, child: Stack(alignment: Alignment.topRight, children: [Opacity(opacity: 0.5, child: CustomImageView(imagePath: ImageConstant.imgEllipse66, height: 129.v, width: 135.h, alignment: Alignment.topLeft)), Opacity(opacity: 0.7, child: CustomImageView(imagePath: ImageConstant.imgEllipse6990x177, height: 90.v, width: 177.h, alignment: Alignment.topRight)), CustomImageView(imagePath: ImageConstant.imgImage93, height: 131.adaptSize, width: 131.adaptSize, alignment: Alignment.bottomCenter)])); } 
/// Section Widget
Widget _buildEmailEditText(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 28.h, right: 30.h), child: CustomTextFormField(controller: emailEditTextController, hintText: "abc@email.com", hintStyle: CustomTextStyles.bodyMediumGray600, textInputType: TextInputType.emailAddress, prefix: Container(margin: EdgeInsets.fromLTRB(15.h, 17.v, 14.h, 17.v), child: CustomImageView(imagePath: ImageConstant.imgCheckmark, height: 22.adaptSize, width: 22.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 56.v))); } 
/// Section Widget
Widget _buildLoginWithGoogleButton(BuildContext context) { return CustomElevatedButton(height: 56.v, text: "Login with Google", leftIcon: Container(margin: EdgeInsets.only(right: 20.h), child: CustomImageView(imagePath: ImageConstant.imgGoogle, height: 26.adaptSize, width: 26.adaptSize)), buttonStyle: CustomButtonStyles.outlineBlueGrayF, buttonTextStyle: CustomTextStyles.bodyLargeAirbnbCerealWBkGray90003); } 
/// Section Widget
Widget _buildSignInButton(BuildContext context) { return CustomElevatedButton(height: 58.v, width: 271.h, text: "Sign in".toUpperCase(), margin: EdgeInsets.only(top: 150.v), rightIcon: Container(padding: EdgeInsets.fromLTRB(8.h, 8.v, 9.h, 9.v), margin: EdgeInsets.only(left: 30.h), decoration: BoxDecoration(color: appTheme.indigoA400, borderRadius: BorderRadius.circular(15.h)), child: CustomImageView(imagePath: ImageConstant.imgArrowleft, height: 13.adaptSize, width: 13.adaptSize)), buttonStyle: CustomButtonStyles.outlineIndigoF, buttonTextStyle: theme.textTheme.titleMedium!, onPressed: () {onTapSignInButton(context);}, alignment: Alignment.topCenter); } 
/// Section Widget
Widget _buildPasswordEditText(BuildContext context) { return Padding(padding: EdgeInsets.only(top: 15.v), child: CustomTextFormField(width: 317.h, controller: passwordEditTextController, hintText: "Your password", hintStyle: CustomTextStyles.bodyMediumGray600, textInputAction: TextInputAction.done, textInputType: TextInputType.visiblePassword, alignment: Alignment.topCenter, prefix: Container(margin: EdgeInsets.fromLTRB(15.h, 17.v, 14.h, 17.v), child: CustomImageView(imagePath: ImageConstant.imgLocation, height: 22.adaptSize, width: 22.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 56.v), suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 16.v, 16.h, 16.v), child: CustomImageView(imagePath: ImageConstant.imgEye, height: 24.adaptSize, width: 24.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 56.v), obscureText: true, contentPadding: EdgeInsets.symmetric(vertical: 18.v))); } 
/// Section Widget
Widget _buildRememberMeRow(BuildContext context) { return Align(alignment: Alignment.topCenter, child: Padding(padding: EdgeInsets.fromLTRB(29.h, 93.v, 29.h, 475.v), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Container(width: 136.h, margin: EdgeInsets.only(bottom: 1.v), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomSwitch(value: isSelectedSwitch, onChange: (value) {isSelectedSwitch = value;}), Text("Remember Me", style: CustomTextStyles.bodyMediumGray90003_1)])), Text("Forgot Password?", style: CustomTextStyles.bodyMediumGray90003_1)]))); } 
/// Navigates to the signUpScreen when the action is triggered.
onTapTxtDonthaveanaccount(BuildContext context) { Navigator.pushNamed(context, AppRoutes.signUpScreen); } 
/// Navigates to the verificationOneScreen when the action is triggered.
onTapSignInButton(BuildContext context) { Navigator.pushNamed(context, AppRoutes.verificationOneScreen); } 
 }
